FROM nginx:latest

RUN echo "<html><body><h1 style='color:red; text-align:center'>nginx-v2</h1></body></html>" > /usr/share/nginx/html/index.html

ENV TERM="xterm-color"
ENV LANG="en_US.UTF-8"
ENV LANGUAGE="en_US.UTF-8"